# Exercise 1: Student Grades Analysis with NumPy

## Context

You are working for a school.  
The administration wants to analyze students' grades before building a reporting system using Pandas.

You receive the following data:

Each row represents a student.

Columns represent:

1. Math grade
2. Physics grade
3. Computer Science grade

```python
import numpy as np

grades = np.array([
    [14, 16, 15],
    [10, 12, 13],
    [18, 17, 19],
    [9, 11, 10],
    [15, 14, 16],
    [13, 15, 12]
])

print(grades)
```

---

## Questions

### Question 1: Explore the Dataset

Display:

- Shape of the dataset
- Number of dimensions
- Total number of elements
- Data type

---

### Question 2: Subject Analysis

Extract and display:

- All Math grades
- All Physics grades
- All Computer Science grades

Then calculate:

- Average grade for each subject
- Maximum grade for each subject
- Minimum grade for each subject

---

### Question 3: Student Performance

Calculate the average grade for each student.

Example idea:

Student 1 average = `(14 + 16 + 15) / 3`

Then:

- Find the best student average
- Find the weakest student average
- Display students whose average is greater than 14

---

### Question 4: Filtering Data

Display:

- Students who scored more than 15 in Math
- Students who failed (average < 10)
- Students who got at least 16 in Computer Science

Use boolean filtering.

---

### Question 5: Bonus Challenge

Create a new column called **Final Average** and append it to the dataset.

Expected structure:

```python
[
 [14,16,15,15.0],
 [10,12,13,11.67],
 ...
]
```

Hint:

Use:

```python
np.column_stack()
```

---

## Skills Practiced

After this exercise, you should be comfortable with:

- Array shape and dimensions
- Indexing and slicing
- `mean()`
- `min()` and `max()`
- `axis=0` and `axis=1`
- Boolean filtering
- Creating new columns
- `np.column_stack()`


In [12]:
# exercise 1 Q1
import numpy as np

grades = np.array([
    [14, 16, 15],
    [10, 12, 13],
    [18, 17, 19],
    [9, 11, 10],
    [15, 14, 16],
    [13, 15, 12]
],dtype=np.float64)

print(grades.shape)
print(grades.ndim)
print(grades.size)
print(grades.dtype)

(6, 3)
2
18
float64


In [17]:
#exercise 1 Q2
print("Math grades : {}".format(grades[:,0]))
print("Physic grades : {}".format(grades[:,1]))
print("Computer Science grades : {}".format(grades[:,2]))

print(grades.mean(axis=0))
print(grades.max(axis=0))
print(grades.min(axis=0))


Math grades : [14. 10. 18.  9. 15. 13.]
Physic grades : [16. 12. 17. 11. 14. 15.]
Computer Science grades : [15. 13. 19. 10. 16. 12.]
[13.16666667 14.16666667 14.16666667]
[18. 17. 19.]
[ 9. 11. 10.]


In [26]:
# exercise 1 Q3
averages = grades.mean(axis=1)
min_grade = np.min(averages)
max_grade = np.max(averages)
print(averages)
print(min_grade)
print(max_grade)

[15.         11.66666667 18.         10.         15.         13.33333333]
10.0
18.0


In [42]:
# exercise 1 Q4
math_grades = grades[:,0]
math_more_1 = grades[grades[:,0]>=15]
print(math_more_1)

[[18. 17. 19.]
 [15. 14. 16.]]


In [45]:
# exerise 1 q5
final_grades = grades.mean(axis=1)
np.column_stack((grades,final_grades))

array([[14.        , 16.        , 15.        , 15.        ],
       [10.        , 12.        , 13.        , 11.66666667],
       [18.        , 17.        , 19.        , 18.        ],
       [ 9.        , 11.        , 10.        , 10.        ],
       [15.        , 14.        , 16.        , 15.        ],
       [13.        , 15.        , 12.        , 13.33333333]])